// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ppqqpgcyajadolbiigqp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBwcXFwZ2N5YWphZG9sYmlpZ3FwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MjEwNzEsImV4cCI6MjA2NTI5NzA3MX0.5JO20rX7Dpcdou4k2feVNXDuUQvEOYgYgVnJzlIpew4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});